# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(blank=True, help_text='Any additional info you consider relevant', max_length=200, null=True, verbose_name='Additional Info')),
            ],
            options={
                'verbose_name': 'Attendee',
                'verbose_name_plural': 'Attendees',
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignation', models.CharField(blank=True, help_text='Assignations given to the user (i.e. Talks, Coffee...)', max_length=200, null=True, verbose_name='Assignation')),
                ('time_availability', models.CharField(blank=True, help_text='Time gap in which you can help during the event. i.e. "All the event", "Morning", "Afternoon"...', max_length=200, null=True, verbose_name='Time Availability')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('additional_info', models.CharField(blank=True, help_text='Any additional info you consider relevant', max_length=200, null=True, verbose_name='Additional Info')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
        migrations.CreateModel(
            name='EventoLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisted', models.BooleanField(default=False, verbose_name='Assisted')),
                ('event', models.ForeignKey(help_text='Event you are going to collaborate', on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name=b'Event')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'EventoL User',
                'verbose_name_plural': 'EventoL User',
            },
        ),
        migrations.CreateModel(
            name='InstalationAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installarion_additional_info', models.TextField(blank=True, help_text='i.e. Wath kind of PC are you bringing', null=True, verbose_name='Additional Info')),
                ('eventolUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EventoLUser', verbose_name='EventoL User')),
            ],
            options={
                'verbose_name': 'Instalation Attendee',
                'verbose_name_plural': 'Instalation Attendees',
            },
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(b'1', 'Beginner'), (b'2', 'Medium'), (b'3', 'Advanced'), (b'4', 'Super Hacker')], help_text='Linux Knowledge level for an installation', max_length=200, verbose_name='Level')),
                ('eventolUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EventoLUser', verbose_name='EventoL User')),
            ],
            options={
                'verbose_name': 'Installer',
                'verbose_name_plural': 'Installers',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventolUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EventoLUser', verbose_name='EventoL User')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='eventolUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EventoLUser', verbose_name='EventoL User'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='eventolUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EventoLUser', verbose_name='EventoL User'),
        ),
    ]
