# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Talk level i.e. Begginer, Expert', max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Talk Level',
                'verbose_name_plural': 'Talk Levels',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='level',
            field=models.ForeignKey(help_text="The talk's Technical level", on_delete=django.db.models.deletion.CASCADE, to='activity.TalkLevel', verbose_name='Level'),
        ),
    ]
