# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Hardware Choice',
                'verbose_name_plural': 'Hardware Choices',
            },
        ),
        migrations.CreateModel(
            name='SoftwareChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Software Choice',
                'verbose_name_plural': 'Software Choices',
            },
        ),
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.HardwareChoices', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.SoftwareChoices', verbose_name='Type'),
        ),
    ]
